### ISSUE TITLE
Add support for CUSTODY-US node type

### ISSUE THREAD

**Issue by lukeasrodgers** [SynapseFI/SynapseFI-Ruby#102]
This is essentially the same issue as #85 but for the `CUSTODY-US` node type.

That issue has been fixed, as I pointed out here -- https://github.com/SynapseFI/SynapseFI-Ruby/pull/86#issuecomment-416402166 -- and can be closed.

**Comment by tynahuynh** [comment]
CUSTODY-US is now added.

**Comment by lukeasrodgers** [comment]
thanks @tynahuynh, you can close #85 as well, it has been fixed for some time
